project:
  type: website
  resources: 
  - shinylive-sw.js

website:
  title: "DLPapp-ERW.github.io"
  navbar:
    left:
      - href: index.qmd 
        text: Dados do leitor de placas 
      - icon: github # add icons that link to social media, etc.
        href: https://github.com/endriowebers

format:
  html:
    theme: 
      - cosmo
      - estilo_ERW.scss


page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Endrio Webers"
    right:
      - icon: github
        href: https://github.com/endriowebers
