on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch: {}

name: demo-website

jobs:
  demo-website:
    runs-on: ubuntu-latest
    concurrency:
      group: quarto-website-${{ github.event_name == 'push' && github.run_id }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Setup pandoc"
        uses: r-lib/actions/setup-pandoc@v2

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2

      - name: "Setup R dependencies for Quarto's knitr engine"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            shinylive@0.3.0
            knitr
            rmarkdown
            downlit
            xml2
            dplyr
            webr

      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Render working directory"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4  # Atualizado para a versão mais recente
        with: 
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: demo-website
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
